In [1]:
import autograd.numpy as anp
from autograd import grad, elementwise_grad, jacobian

In [5]:
def f11(x):
    return x**2

g = grad(f11)
g(3.0)

np.float64(6.0)

In [10]:
h = elementwise_grad(f11)
h(anp.array([3.0, 4.0, 5.0]))

array([ 6.,  8., 10.])

In [9]:
j = jacobian(f11)
j(anp.array([3.0, 4.0, 5.0]))

array([[ 6.,  0.,  0.],
       [ 0.,  8.,  0.],
       [ 0.,  0., 10.]])

In [ ]:
def f1n(x):
    # [1 ]
    # [2x]
    return anp.array([ x, x**2 ])

g = elementwise_grad(f1n)
g(3.0)

np.float64(7.0)

In [21]:
j = jacobian(f1n)
j(3.0)

array([1., 6.])

In [24]:
j(anp.array([3.0,4.0]))

array([[[1., 0.],
        [0., 1.]],

       [[6., 0.],
        [0., 8.]]])

In [32]:
def fnm(X):
    x,y = X
    # [ -1  1 ]
    # [ 2x 2y ]
    return anp.array([ - x + y, x**2 + y**2 ])

X = anp.array([3.0,4.0])
h = elementwise_grad(fnm)
h(X)

array([5., 9.])

In [28]:
j = jacobian(fnm)
j(X)

array([[-1.,  1.],
       [ 6.,  8.]])

In [33]:
def fnm(X):
    x,y = X
    # [ -1  1 ]
    # [ 2x 2y ]
    return anp.array([ lambda x,y: - x + y, lambda x,y:x**2 + y**2 ])

X = anp.array([3.0,4.0])
h = elementwise_grad(fnm)
h(X)

array([0., 0.])

In [ ]:
def backward(functions, values):
    def 
    return elementwise_grad(functions)(values)

functions = [lambda x:x, lambda x:x**2, lambda x:x**3]
backward(functions, [1.0,2.0,3.0])

TypeError: 'numpy.ndarray' object is not callable

In [41]:
def a(x): return x**2
def b(x): return x**3

fs = [a,b]
g = elementwise_grad(fs)
# g(anp.array([1.0,1.0]))
g(1.0,1.0)

TypeError: 'list' object is not callable