In [ ]:
import numpy as np
a = np.array(
    [[ [0,0,0],[1,1,1] ], 
     [ [3,4,5],[7,8,9] ],
     [ [3,1,4],[1,5,9] ],
     [ [0,6,9],[4,2,0] ] ]
)

print(np.stack(a, axis=0))
print(np.stack(a, axis=0).shape)
print()
print(np.stack(a, axis=1))
print(np.stack(a, axis=1).shape)
print()

print(np.stack(a, axis=-1))
print(np.stack(a, axis=-1).shape)

[[[0 0 0]
  [1 1 1]]

 [[3 4 5]
  [7 8 9]]

 [[3 1 4]
  [1 5 9]]

 [[0 6 9]
  [4 2 0]]]
(4, 2, 3)

[[[0 0 0]
  [3 4 5]
  [3 1 4]
  [0 6 9]]

 [[1 1 1]
  [7 8 9]
  [1 5 9]
  [4 2 0]]]
(2, 4, 3)

[[[0 3 3 0]
  [0 4 1 6]
  [0 5 4 9]]

 [[1 7 1 4]
  [1 8 5 2]
  [1 9 9 0]]]
(2, 3, 4)
