In [2]:
import numpy as np

In [ ]:
# np.stack, axis

a = np.array(
    [[ [0,0,0],[1,1,1] ], 
     [ [3,4,5],[7,8,9] ],
     [ [3,1,4],[1,5,9] ],
     [ [0,6,9],[4,2,0] ] ]
)

print(np.stack(a, axis=0))
print(np.stack(a, axis=0).shape)
print()
print(np.stack(a, axis=1))
print(np.stack(a, axis=1).shape)
print()

print(np.stack(a, axis=-1))
print(np.stack(a, axis=-1).shape)

In [ ]:
# np.newaxis

a = np.array([1,2,3])
b = np.array([4,5])

print(a.shape)
print(b.shape)

print(a)
print(b)

try:
    print(a * b)
except Exception as e:
    print("error:", e)
    a = a[..., np.newaxis]
    b = b[np.newaxis, ...]
    print(a)
    print(b)
    print(a * b)

(3,)
(2,)
[1 2 3]
[4 5]
error: operands could not be broadcast together with shapes (3,) (2,) 
[[1]
 [2]
 [3]]
[[4 5]]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# v.shape

s = np.array(42)
a = np.array([1,2,3])
b = np.array([[1,2,3]])
c = np.array([[1],[2],[3]])

d = a[np.newaxis, ...] # turn a into row vector
e = a[..., np.newaxis] # turn a into col vector

f = c[..., 0]
g = c[..., None]

for v in (s,a,b,c,d,e,f,g):
    print(v)
    print(v.shape, end='\n\n')

print(np.newaxis)

42
()

[1 2 3]
(3,)

[[1 2 3]]
(1, 3)

[[1]
 [2]
 [3]]
(3, 1)

[[1 2 3]]
(1, 3)

[[1]
 [2]
 [3]]
(3, 1)

[1 2 3]
(3,)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)

None


In [ ]:
# array indexing
# [:] slice operator
# [...] elilipsis operator
# None = np.newaxis = 'add axis 1 here'

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in (
    a, a[0], a[0,0], a[:], a[:, 0], a[0, :], a[:,:], 
    a[:, None], a[None, :], a[..., None], a[None, None],
    a[..., 0], a[0, ..., None]
):
    print(x)
    print(x.shape, end='\n\n')

print(slice(None))
print(Ellipsis)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[1 2 3]
(3,)

1
()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[1 4 7]
(3,)

[1 2 3]
(3,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
(1, 1, 3, 3)

[1 4 7]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

slice(None, None, None)
Ellipsis


In [52]:
# how np takes tuples as indices

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:, 0])
print(a.__getitem__( (slice(None), 0) ))

print(a[None, ...])
print(a.__getitem__( (None, Ellipsis) ))

[1 4 7]
[1 4 7]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# broadcasting with *
# short.rfill(1)
# if !(short[i] == long[i] or short[i] == 1]) return error
# short[i] = long[i]

AB = [
    [ [1,2,3],              [[4],[5]]   ],
    [ [[1],[2],[3]],        [4,5]       ], 
    [ [[1,1],[2,2],[3,3]],  [4,5]       ],
    [ [[1,0],[2,0],[3,0]],  [4,5]       ]
]

for (a,b) in AB:
    a,b = np.array(a), np.array(b)
    print(a)
    print(a.shape)
    print(b)
    print(b.shape)
    print(a*b)
    print((a*b).shape, end='\n\n')

[1 2 3]
(3,)
[[4]
 [5]]
(2, 1)
[[ 4  8 12]
 [ 5 10 15]]
(2, 3)

[[1]
 [2]
 [3]]
(3, 1)
[4 5]
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]
(3, 2)

[[1 1]
 [2 2]
 [3 3]]
(3, 2)
[4 5]
(2,)
[[ 4  5]
 [ 8 10]
 [12 15]]
(3, 2)

[[1 0]
 [2 0]
 [3 0]]
(3, 2)
[4 5]
(2,)
[[ 4  0]
 [ 8  0]
 [12  0]]
(3, 2)



In [82]:
x = np.array(10)
y = np.array([[10]])
a = np.array([[6,9],[4,2],[6,9]])

for v in (x,y):
    print(v.shape)
    print(a.shape)
    print(v*a)

()
(3, 2)
[[60 90]
 [40 20]
 [60 90]]
(1, 1)
(3, 2)
[[60 90]
 [40 20]
 [60 90]]


In [86]:
a = np.array([[[3],[4],[5]]])
b = np.squeeze(a)
print(a, a.shape)
print(b, b.shape)

[[[3]
  [4]
  [5]]] (1, 3, 1)
[3 4 5] (3,)


In [ ]:
a = np.array([1,2,3])
b = a[..., None] # col vec
c = a[None, ...] # row vec

v = np.array([6,9])
print(a*a) # (3,) * (3,) = (3,)
print(b*v) # (3,1) * (2,) = (3,2)
print(c*v) # (1,3) * (2,) = error

[1 4 9]
[[ 6  9]
 [12 18]
 [18 27]]


ValueError: operands could not be broadcast together with shapes (1,3) (2,) 