In [1]:
import numpy as np

In [ ]:
def full_corr(k,x):
    pad = len(k)-1
    p = np.hstack([
        np.zeros(pad),
        x,
        np.zeros(pad)]
    )
    return np.array([ np.dot(k, p[i:i+len(k)]) for i in range(len(p)-len(k)+1) ])

def full_conv(a,b):
    return full_corr(np.flip(a), b)

In [108]:
k = [1,2]
x = [3,4,5]
print(full_corr(k,x))
print(full_corr(x,k))
print(full_conv(k,x))
print(full_conv(x,k))

[ 6. 11. 14.  5.]
[ 5. 14. 11.  6.]
[ 3. 10. 13. 10.]
[ 3. 10. 13. 10.]


In [109]:
x = [0,1]
y = [1,2,1]
z = [1,1]
print(full_corr(full_corr(x,y),z))
print(full_corr(x,full_corr(y,z)))

print(full_conv(full_conv(x,y),z))
print(full_conv(x,full_conv(y,z)))

[0. 1. 3. 3. 1.]
[1. 3. 3. 1. 0.]
[0. 1. 3. 3. 1.]
[0. 1. 3. 3. 1.]


In [111]:
x = [2,1,0,4,1,3]
k = [1,3,2,1]
print(full_conv(k,x))
print(full_corr(k,x))

[ 2.  7.  7.  8. 14. 14. 15.  7.  3.]
[ 2.  5.  8.  9. 10. 17. 13. 10.  3.]
