In [4]:
import numpy as np

In [28]:
def hz(z, x):
    a, b = np.array(z[0]), np.array(z[1])
    print(a[..., np.newaxis].shape, b[..., np.newaxis].shape, x.shape)
    return 1 / (1 + a[..., np.newaxis] * np.exp(- b[..., np.newaxis] * x))

def my_hz(z,x):
    a, b = np.array(z[0]), np.array(z[1])
    print(a.shape, b.shape, x.shape)
    return 1 / (1 + a * np.exp(- b * x))

In [48]:
def risk(z, x, y):
    y_hat = hz(z, x)
    print(y_hat, y_hat.shape)
    print(y[np.newaxis, np.newaxis, ...], y[np.newaxis, np.newaxis, ...].shape)
    return np.squeeze(np.mean((y[np.newaxis, np.newaxis, ...] - y_hat) ** 2, axis=-1))

def my_risk(z, x, y):
    y_hat = hz(z, x)
    print(y_hat, y_hat.shape)
    print(y, y.shape)
    print((y - y_hat) ** 2)
    return np.mean((y - y_hat) ** 2, axis=-1)

In [49]:
a = np.array([.1,.2,.3])
b = np.array([.4,.5,.6])
x = np.array([4,2])
y = np.array([6,9])

# print(hz([a,b],x))
# print(my_hz([a,b],x))

print(risk([a,b],x,y))
print()
print(my_risk([a,b],x,y))

(3, 1) (3, 1) (2,)
[[0.9802099  0.95699925]
 [0.97364626 0.93146652]
 [0.97350567 0.91712975]] (3, 2)
[[[6 9]]] (1, 1, 2)
[44.94407683 45.18273219 45.29921839]

(3, 1) (3, 1) (2,)
[[0.9802099  0.95699925]
 [0.97364626 0.93146652]
 [0.97350567 0.91712975]] (3, 2)
[6 9] (2,)
[[25.19829261 64.68986104]
 [25.2642319  65.10123247]
 [25.26564527 65.3327915 ]]
[44.94407683 45.18273219 45.29921839]
